[bell]
animation = "Linear"
color = "#b59b9c"
duration = 500

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 22

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[hints]
alphabet = "jfkdls;ahgurieowpq"
enabled = [
    { regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\\u0000-\\u001F\\u007F-\\u009F<>\"\\s{-}\\^⟨⟩`]+", action = "Copy" }
]
[scrolling]
multiplier = 15

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',│`|:"' ()[]{}<>	'''

[window]
decorations = "transparent"
dynamic_padding = false
dynamic_title = false
opacity = 1
startup_mode = "Windowed"

[window.dimensions]
columns = 150
lines = 45

[window.padding]
x = 21
y = 21

[window.position]
x = 2500
y = 700

[general]
live_config_reload = true

# [terminal]
# [terminal.shell]
# program = "/bin/zsh"
# args = ["-l", "-c", "~/.config/tmux/session-init.sh"]

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "W"
mods = "Command"
action = "Quit"

[[keyboard.bindings]]
key = "D"
mods = "Command"
action = "CreateNewWindow"

# Gruvbox Color Scheme
[colors]
  [colors.primary]
  background = "#282828"  # dark gruvbox background
  foreground = "#ebdbb2"  # light gruvbox foreground

  [colors.normal]
  black   = "#1d2021"  # gruvbox dark black
  red     = "#fb4934"  # gruvbox red
  green   = "#85e054"  # gruvbox green
  yellow  = "#fece56"  # gruvbox yellow
  blue    = "#83a598"  # gruvbox blue
  magenta = "#d3869b"  # gruvbox magenta
  cyan    = "#8ec07c"  # gruvbox cyan
  white   = "#ebdbb2"  # gruvbox white

  [colors.bright]
  black   = "#928374"  # gruvbox bright black
  red     = "#fb4934"  # gruvbox bright red
  green   = "#8ec07c"  # gruvbox bright green
  yellow  = "#f9f1a5"  # gruvbox bright yellow
  blue    = "#83a598"  # gruvbox bright blue
  magenta = "#d3869b"  # gruvbox bright magenta
  cyan    = "#8ec07c"  # gruvbox bright cyan
  white   = "#f2e5bc"  # gruvbox bright white
